In [29]:
import pandas as pd
import numpy as np

In [30]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day28_pandas_aggregation.csv")

In [31]:
df.head()

,Order_ID,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,2801,Hyderabad,Laptop,Electronics,1,55000,Delivered,55000
1,2802,Bengaluru,Mouse,Accessories,3,700,Delivered,2100
2,2803,Chennai,Keyboard,Accessories,2,1200,Cancelled,2400
3,2804,Hyderabad,Monitor,Electronics,1,14000,Delivered,14000
4,2805,Vijayawada,Mouse,Accessories,4,700,Delivered,2800

In [32]:
df.shape

(30, 8)

In [33]:
df.columns

Index(['Order_ID', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price_INR',
       'Order_Status', 'Revenue_INR'],
      dtype='object')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   City            30 non-null     object
 2   Product         30 non-null     object
 3   Category        30 non-null     object
 4   Quantity        30 non-null     int64
 5   Unit_Price_INR  30 non-null     int64
 6   Order_Status    30 non-null     object
 7   Revenue_INR     30 non-null     int64
dtypes: int64(4), object(4)
memory usage: 2.0+ KB

In [63]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR    Revenue_INR
count    30.000000  30.000000        30.00000      30.000000
mean   2815.500000   2.200000     16590.00000   21233.333333
std       8.803408   1.297212     22209.54051   30684.224109
min    2801.000000   1.000000       700.00000    1400.000000
25%    2808.250000   1.000000       700.00000    2500.000000
50%    2815.500000   2.000000      1200.00000    4200.000000
75%    2822.750000   3.000000     14000.00000   14000.000000
max    2830.000000   5.000000     55000.00000  110000.000000

In [35]:
df.isnull().sum()

Order_ID          0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Order_Status      0
Revenue_INR       0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
# Total revenue
df["Revenue_INR"].sum()

np.int64(637000)

In [38]:
# Average revenue
df["Revenue_INR"].mean()

np.float64(21233.333333333332)

In [39]:
# Total quantity sold
df["Quantity"].sum()

np.int64(66)

In [40]:
# Average product price
df["Unit_Price_INR"].mean()

np.float64(16590.0)

In [41]:
# Highest product price
df["Unit_Price_INR"].max()

np.int64(55000)

In [42]:
# Lowest product price
df["Unit_Price_INR"].min()

np.int64(700)

In [43]:
# Median revenue
df["Revenue_INR"].median()

np.float64(4200.0)

In [44]:
# Number of recorded order IDs
df["Order_ID"].count()

np.int64(30)

In [45]:
# Number of unique products
df["Product"].unique()

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], dtype=object)

In [46]:
# Total revenue by city
total_revenue=df.groupby("City")["Revenue_INR"].sum()
total_revenue

City
Bengaluru     109000
Chennai       190100
Hyderabad     152300
Vijayawada    185600
Name: Revenue_INR, dtype: int64

In [49]:
# Average revenue by city
avg=df.groupby("City")["Revenue_INR"].mean()
avg

City
Bengaluru     13625.000000
Chennai       23762.500000
Hyderabad     19037.500000
Vijayawada    30933.333333
Name: Revenue_INR, dtype: float64

In [52]:
# Total quantity by product
total=df.groupby("Product")["Quantity"].sum()
total

Product
Keyboard    18
Laptop       9
Monitor      7
Mouse       32
Name: Quantity, dtype: int64

In [54]:
# Highest price by product
highest=df.groupby("Product")["Unit_Price_INR"].max()
highest

Product
Keyboard     1200
Laptop      55000
Monitor     14000
Mouse         700
Name: Unit_Price_INR, dtype: int64

In [56]:
# Order count by status
count=df.groupby("Order_Status")["Order_ID"].count()
count

Order_Status
Cancelled     5
Delivered    22
Returned      3
Name: Order_ID, dtype: int64

In [57]:
# Revenue by category
df.groupby("Category")["Revenue_INR"].sum()

Category
Accessories     44000
Electronics    593000
Name: Revenue_INR, dtype: int64

In [58]:
# Revenue and quantity by city
df.groupby("City").agg(
    Total_Revenue=("Revenue_INR", "sum"),
    Total_Quantity=("Quantity", "sum"))

            Total_Revenue  Total_Quantity
City
Bengaluru          109000              19
Chennai            190100              17
Hyderabad          152300              18
Vijayawada         185600              12

In [59]:
# Multiple metrics by product
df.groupby("Product").agg(
    Total_Revenue=("Revenue_INR", "sum"),
    Average_Revenue=("Revenue_INR", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Order_Count=("Order_ID", "count"),
    Highest_Price=("Unit_Price_INR", "max"))

,Total_Revenue,Average_Revenue,Total_Quantity,Order_Count,Highest_Price
Product,,,,,
Keyboard,21600,3085.714286,18,7,1200
Laptop,495000,70714.285714,9,7,55000
Monitor,98000,14000.000000,7,7,14000
Mouse,22400,2488.888889,32,9,700

In [60]:
# Multiple metrics by order status
df.groupby("Order_Status").agg(
    Order_Count=("Order_ID", "count"),
    Total_Revenue=("Revenue_INR", "sum"),
    Average_Revenue=("Revenue_INR", "mean"))

              Order_Count  Total_Revenue  Average_Revenue
Order_Status
Cancelled               5          90200     18040.000000
Delivered              22         422800     19218.181818
Returned                3         124000     41333.333333

In [61]:
# Find products with highest total revenue
df.groupby("Product")["Revenue_INR"].sum().sort_values(ascending=False)

Product
Laptop      495000
Monitor      98000
Mouse        22400
Keyboard     21600
Name: Revenue_INR, dtype: int64

In [62]:
# Create a city-wise sales report
sales_report = df.groupby("City", as_index=False).agg(
    Total_Revenue=("Revenue_INR", "sum"),
    Average_Revenue=("Revenue_INR", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Order_Count=("Order_ID", "count"))
sales_report

         City  Total_Revenue  Average_Revenue  Total_Quantity  Order_Count
0   Bengaluru         109000     13625.000000              19            8
1     Chennai         190100     23762.500000              17            8
2   Hyderabad         152300     19037.500000              18            8
3  Vijayawada         185600     30933.333333              12            6