In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day18_employee_data.csv")

In [4]:
df.head()

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
0,2001,Ravi,IT,Data Analyst,Hyderabad,24,1,35000.0,4.2,2024-06-10,Active
1,2002,Asha,HR,HR Executive,Bengaluru,29,5,42000.0,4.0,2021-03-15,Active
2,2003,Sandeep,IT,Python Developer,Hyderabad,23,1,40000.0,4.5,2025-01-20,Active
3,2004,Neha,Sales,Sales Executive,Chennai,31,7,38000.0,3.8,2019-08-12,Active
4,2005,Kiran,Finance,Accountant,Pune,35,10,60000.0,NaN,2016-04-01,Active

In [5]:
df.tail()

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
20,2021,Rohit,IT,BI Analyst,Hyderabad,27,3,50000.0,4.5,NaN,Active
21,2022,Isha,HR,HR Executive,Bengaluru,30,6,46000.0,4.1,2020-12-07,On Leave
22,2023,Ajay,Finance,Financial Analyst,Pune,38,13,72000.0,4.4,2013-07-30,Active
23,2024,Nandini,IT,Data Analyst,Hyderabad,25,2,53000.0,4.6,2024-09-02,Active
24,2025,Teja,Sales,Sales Executive,Chennai,28,4,39000.0,3.9,2021-02-11,Active

In [6]:
df.shape

(25, 11)

In [7]:
df.size

275

In [8]:
df.sample(5,random_state=42)

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
8,2009,Manoj,Finance,Accountant,NaN,37,12,62000.0,4.0,2014-09-22,Active
16,2017,Varun,IT,Data Scientist,Bengaluru,29,5,70000.0,4.6,2020-08-24,Active
0,2001,Ravi,IT,Data Analyst,Hyderabad,24,1,35000.0,4.2,2024-06-10,Active
23,2024,Nandini,IT,Data Analyst,Hyderabad,25,2,53000.0,4.6,2024-09-02,Active
11,2012,Ananya,IT,Data Analyst,Hyderabad,27,4,52000.0,4.5,2022-10-03,Active

In [9]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Role', 'City', 'Age',
       'Experience_Years', 'Monthly_Salary_INR', 'Performance_Rating',
       'Joining_Date', 'Employment_Status'],
      dtype='object')

In [10]:
df.dtypes

Employee_ID             int64
Employee_Name          object
Department             object
Job_Role               object
City                   object
Age                     int64
Experience_Years        int64
Monthly_Salary_INR    float64
Performance_Rating    float64
Joining_Date           object
Employment_Status      object
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         25 non-null     int64
 1   Employee_Name       25 non-null     object
 2   Department          25 non-null     object
 3   Job_Role            25 non-null     object
 4   City                24 non-null     object
 5   Age                 25 non-null     int64
 6   Experience_Years    25 non-null     int64
 7   Monthly_Salary_INR  24 non-null     float64
 8   Performance_Rating  24 non-null     float64
 9   Joining_Date        24 non-null     object
 10  Employment_Status   25 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 2.3+ KB

In [13]:
df.describe()

,Employee_ID,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating
count,25.000000,25.000000,25.0000,24.000000,24.000000
mean,2013.000000,29.640000,5.8400,49875.000000,4.191667
std,7.359801,4.572381,3.8371,11862.665219,0.288801
min,2001.000000,23.000000,1.0000,35000.000000,3.700000
25%,2007.000000,26.000000,3.0000,40750.000000,3.975000
50%,2013.000000,29.000000,5.0000,45500.000000,4.200000
75%,2019.000000,32.000000,8.0000,58500.000000,4.425000
max,2025.000000,39.000000,14.0000,75000.000000,4.700000

In [15]:
df.describe(include="all")

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
count,25.000000,25,25,25,24,25.000000,25.0000,24.000000,24.000000,24,25
unique,NaN,25,4,9,4,NaN,NaN,NaN,NaN,24,2
top,NaN,Ravi,IT,Sales Executive,Hyderabad,NaN,NaN,NaN,NaN,2024-06-10,Active
freq,NaN,1,9,6,9,NaN,NaN,NaN,NaN,1,23
mean,2013.000000,NaN,NaN,NaN,NaN,29.640000,5.8400,49875.000000,4.191667,NaN,NaN
std,7.359801,NaN,NaN,NaN,NaN,4.572381,3.8371,11862.665219,0.288801,NaN,NaN
min,2001.000000,NaN,NaN,NaN,NaN,23.000000,1.0000,35000.000000,3.700000,NaN,NaN
25%,2007.000000,NaN,NaN,NaN,NaN,26.000000,3.0000,40750.000000,3.975000,NaN,NaN
50%,2013.000000,NaN,NaN,NaN,NaN,29.000000,5.0000,45500.000000,4.200000,NaN,NaN
75%,2019.000000,NaN,NaN,NaN,NaN,32.000000,8.0000,58500.000000,4.425000,NaN,NaN
max,2025.000000,NaN,NaN,NaN,NaN,39.000000,14.0000,75000.000000,4.700000,NaN,NaN

In [26]:
# Count unique values
df['Department'].nunique()

4

In [27]:
df["City"].nunique()

4

In [30]:
df["Job_Role"].nunique()

9

In [ ]:
# unique() — display the distinct values

In [21]:
df["Department"].unique()

array(['IT', 'HR', 'Sales', 'Finance'], dtype=object)

In [24]:
df["City"].unique()

array(['Hyderabad', 'Bengaluru', 'Chennai', 'Pune', nan], dtype=object)

In [25]:
df["Employment_Status"].unique()

array(['Active', 'On Leave'], dtype=object)

In [31]:
# value_counts() — frequency of each value
print(df["Department"].value_counts())

Department
IT         9
Sales      6
HR         5
Finance    5
Name: count, dtype: int64

In [32]:
# To include missing values in the counts
print(df["City"].value_counts(dropna=False))

City
Hyderabad    9
Chennai      6
Bengaluru    5
Pune         4
NaN          1
Name: count, dtype: int64

unique()	    Returns distinct values
nunique()	    Counts distinct values
value_counts()	Counts how often each value occurs

In [35]:
# Count employees in each department
df["Department"].value_counts()

Department
IT         9
Sales      6
HR         5
Finance    5
Name: count, dtype: int64

In [36]:
# Find the highest salary
df["Monthly_Salary_INR"].max()

np.float64(75000.0)

In [46]:
# Find the employee with the highest salary:
df.loc[df["Monthly_Salary_INR"].idxmax(),["Employee_Name", "Department", "Monthly_Salary_INR"]]

Employee_Name          Vikram
Department            Finance
Monthly_Salary_INR    75000.0
Name: 12, dtype: object

In [47]:
# Find employees with more than 5 years of experience
df[df["Experience_Years"]>5]

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
3,2004,Neha,Sales,Sales Executive,Chennai,31,7,38000.0,3.8,2019-08-12,Active
4,2005,Kiran,Finance,Accountant,Pune,35,10,60000.0,NaN,2016-04-01,Active
7,2008,Divya,HR,Recruiter,Chennai,30,6,45000.0,4.3,2020-02-17,Active
8,2009,Manoj,Finance,Accountant,NaN,37,12,62000.0,4.0,2014-09-22,Active
10,2011,Rahul,Sales,Sales Executive,Chennai,32,8,39000.0,3.7,2018-05-14,Active
12,2013,Vikram,Finance,Financial Analyst,Pune,39,14,75000.0,4.2,2012-12-11,Active
15,2016,Meera,Sales,Sales Executive,Chennai,33,9,42000.0,3.9,2017-03-06,Active
17,2018,Kavya,Finance,Accountant,Pune,36,11,58000.0,4.0,2015-11-16,On Leave
19,2020,Lakshmi,Sales,Sales Executive,Chennai,31,7,41000.0,3.8,2019-01-25,Active
21,2022,Isha,HR,HR Executive,Bengaluru,30,6,46000.0,4.1,2020-12-07,On Leave
22,2023,Ajay,Finance,Financial Analyst,Pune,38,13,72000.0,4.4,2013-07-30,Active

In [48]:
# nspect missing values
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Department            0
Job_Role              0
City                  1
Age                   0
Experience_Years      0
Monthly_Salary_INR    1
Performance_Rating    1
Joining_Date          1
Employment_Status     0
dtype: int64

In [49]:
print("Total missing cells:",df.isnull().sum().sum())

Total missing cells: 4

In [50]:
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0