In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day26_pandas_datetime.csv")

In [3]:
df.head()

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Order_Date,Order_Status,Revenue_INR
0,5001,Sandeep,Hyderabad,Laptop,1,55000,2026-01-03,Delivered,55000
1,5002,Ravi,Bengaluru,Mouse,2,800,2026-01-15,Delivered,1600
2,5003,Priya,Chennai,Monitor,1,12500,2026-02-02,Returned,12500
3,5004,Anil,Pune,Keyboard,1,1500,2026-02-18,Delivered,1500
4,5005,Divya,Hyderabad,Laptop,1,62000,2026-03-05,Cancelled,62000

In [4]:
df.shape

(30, 9)

In [5]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Quantity',
       'Unit_Price_INR', 'Order_Date', 'Order_Status', 'Revenue_INR'],
      dtype='object')

In [22]:
df.describe()

,Order_ID,Quantity,Unit_Price_INR,Order_Date,Revenue_INR,Year,Month,Day,Quarter,Days_Since_Order
count,30.000000,30.000000,30.000000,30,30.000000,30.0,30.000000,30.000000,30.000000,30.000000
mean,5015.500000,1.666667,25200.000000,2026-06-15 18:24:00,26551.666667,2026.0,6.066667,13.600000,2.400000,130.233333
min,5001.000000,1.000000,650.000000,2026-01-03 00:00:00,1500.000000,2026.0,1.000000,1.000000,1.000000,1.000000
25%,5008.250000,1.000000,1412.500000,2026-04-04 06:00:00,2825.000000,2026.0,4.000000,4.250000,2.000000,52.000000
50%,5015.500000,1.000000,12250.000000,2026-06-22 00:00:00,12750.000000,2026.0,6.000000,14.000000,2.000000,124.000000
75%,5022.750000,2.000000,57750.000000,2026-09-02 00:00:00,57750.000000,2026.0,8.750000,20.750000,3.000000,202.750000
max,5030.000000,5.000000,64000.000000,2026-10-23 00:00:00,64000.000000,2026.0,10.000000,30.000000,4.000000,294.000000
std,8.803408,1.028334,27061.969116,NaN,26297.969252,0.0,2.911728,9.305542,1.037238,89.831138

In [23]:
df.size

510

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
City              0
Product           0
Quantity          0
Unit_Price_INR    0
Order_Date        0
Order_Status      0
Revenue_INR       0
dtype: int64

# Convert text to datetime
- Use pd.to_datetime():

In [8]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
print(df.dtypes)

Order_ID                   int64
Customer_Name             object
City                      object
Product                   object
Quantity                   int64
Unit_Price_INR             int64
Order_Date        datetime64[ns]
Order_Status              object
Revenue_INR                int64
dtype: object

In [9]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day
print(df[["Order_Date", "Year", "Month", "Day"]].head())

  Order_Date  Year  Month  Day
0 2026-01-03  2026      1    3
1 2026-01-15  2026      1   15
2 2026-02-02  2026      2    2
3 2026-02-18  2026      2   18
4 2026-03-05  2026      3    5

In [10]:
df["Month_Name"] = df["Order_Date"].dt.month_name()
df["Day_Name"] = df["Order_Date"].dt.day_name()
df["Quarter"] = df["Order_Date"].dt.quarter

# Filter data using dates
- Example 1: Orders after June 1, 2026

In [13]:
result = df[df["Order_Date"] >= "2026-06-01"].head()
result

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Order_Date,Order_Status,Revenue_INR,Year,Month,Day,Month_Name,Day_Name,Quarter
13,5014,Manoj,Bengaluru,Keyboard,2,1600,2026-06-04,Delivered,3200,2026,6,4,June,Thursday,2
14,5015,Harsha,Chennai,Laptop,1,57000,2026-06-16,Returned,57000,2026,6,16,June,Tuesday,2
15,5016,Asha,Pune,Monitor,2,12000,2026-06-28,Delivered,24000,2026,6,28,June,Sunday,2
16,5017,Naveen,Hyderabad,Mouse,5,650,2026-07-02,Delivered,3250,2026,7,2,July,Thursday,3
17,5018,Geetha,Bengaluru,Laptop,1,64000,2026-07-11,Delivered,64000,2026,7,11,July,Saturday,3

In [15]:
# Example 2: Orders from March 1 to March 31
result = df[
    (df["Order_Date"] >= "2026-03-01") &
    (df["Order_Date"] < "2026-04-01")]

result

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Order_Date,Order_Status,Revenue_INR,Year,Month,Day,Month_Name,Day_Name,Quarter
4,5005,Divya,Hyderabad,Laptop,1,62000,2026-03-05,Cancelled,62000,2026,3,5,March,Thursday,1
5,5006,Kiran,Bengaluru,Monitor,2,11800,2026-03-12,Delivered,23600,2026,3,12,March,Thursday,1
6,5007,Meena,Chennai,Mouse,3,750,2026-03-22,Delivered,2250,2026,3,22,March,Sunday,1

In [17]:
# Example 3: Orders from October
october_orders = df[df["Order_Date"].dt.month == 10]
october_orders

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Order_Date,Order_Status,Revenue_INR,Year,Month,Day,Month_Name,Day_Name,Quarter
25,5026,Teja,Bengaluru,Monitor,1,12700,2026-10-01,Cancelled,12700,2026,10,1,October,Thursday,4
26,5027,Mounika,Chennai,Mouse,3,850,2026-10-08,Delivered,2550,2026,10,8,October,Thursday,4
27,5028,Sai,Pune,Laptop,1,63000,2026-10-14,Delivered,63000,2026,10,14,October,Wednesday,4
28,5029,Nikhil,Hyderabad,Keyboard,1,1550,2026-10-20,Delivered,1550,2026,10,20,October,Tuesday,4
29,5030,Bhavya,Bengaluru,Laptop,1,60500,2026-10-23,Delivered,60500,2026,10,23,October,Friday,4

# Calculate date differences
- Suppose we want to calculate how many days have passed since each order date, using October 24, 2026, as the reference date.

In [18]:
reference_date = pd.Timestamp("2026-10-24")
df["Days_Since_Order"] = (reference_date - df["Order_Date"]).dt.days
print(df[["Order_Date", "Days_Since_Order"]].head())

  Order_Date  Days_Since_Order
0 2026-01-03               294
1 2026-01-15               282
2 2026-02-02               264
3 2026-02-18               248
4 2026-03-05               233

# Format dates as strings

In [19]:
df["Formatted_Date"] = df["Order_Date"].dt.strftime("%d-%m-%Y")
print(df[["Order_Date", "Formatted_Date"]].head())

  Order_Date Formatted_Date
0 2026-01-03     03-01-2026
1 2026-01-15     15-01-2026
2 2026-02-02     02-02-2026
3 2026-02-18     18-02-2026
4 2026-03-05     05-03-2026

In [20]:
# Handle invalid or missing dates
dates = pd.Series([
    "2026-01-15",
    "not-a-date",
    None])

converted_dates = pd.to_datetime(
    dates,
    errors="coerce")
print(converted_dates)

0   2026-01-15
1          NaT
2          NaT
dtype: datetime64[ns]

In [21]:
print(df["Order_Date"].isna().sum())

0